export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD = 'ADD';
export const SUBTRACT = 'SUBTRACT';
export const STORE_RESULT = 'STORE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';

//fetching stories
export const FETCH_STORIES_START = 'FETCH_STORIES_START';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAIL = 'FETCH_STORIES_FAIL';

//fetch single story

export const FETCH_STORY_START = 'FETCH_STORY_START';
export const FETCH_STORY_SUCCESS = 'FETCH_STORY_SUCCESS';
export const FETCH_STORY_FAIL = 'FETCH_STORY_FAIL';

//post

export const POST_STORY_START = 'POST_STORY_START';
export const POST_STORY_SUCCESS = 'POST_STORY_SUCCESS';
export const POST_STORY_FAIL = 'POST_STORY_FAIL';

//delete

export const DELETE_STORY_START = 'DELETE_STORY_START';
export const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';
export const DELETE_STORY_FAIL = 'DELETE_STORY_FAIL';







